# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Personal_PlayGrounds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'

  # Pods for Personal_PlayGrounds

  target 'Personal_PlayGroundsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Personal_PlayGroundsUITests' do
    # Pods for testing
  end

end
